apiVersion: apps/v1
kind: Deployment
metadata:
  name: netcore-graph-api-deployment
spec:
  selector:
    matchLabels:
      app: netcore-graph-api-pod
  template:
    metadata:
      labels:
        app: netcore-graph-api-pod
    spec:
      containers:
      - name: netcore-graph-api-container
        image: localhost:5000/api:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5001
